version: '3.8'
services:
  db:
    container_name: db
    image: postgres:latest
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      DB_NAME: mnist_predictions
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - app_network

  api:
    build: ./model
    container_name: mnist_api
    ports:
      - "8000:8000"  # Expose FastAPI on port 8000
    networks:
      - app_network

  streamlit:
    container_name: app
    build: ./app
    environment:
      FASTAPI_URL: "http://api:8000" 
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
    ports:
      - "8501:8501"
    depends_on:
      - db
      - api
    networks:
      - app_network

networks:
  app_network:
    driver: bridge

volumes:
  db_data:
